// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BieL_TyFaQFmU-8YLnhEHa9rgA8i7SM',
    appId: '1:317429734420:web:fababf985b8cb212a11b01',
    messagingSenderId: '317429734420',
    projectId: 'thickthock',
    authDomain: 'thickthock.firebaseapp.com',
    storageBucket: 'thickthock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6vw30uzAxppUQSnntWzvjkcUPrHPMfRg',
    appId: '1:317429734420:android:ef5896b3e4a4c01aa11b01',
    messagingSenderId: '317429734420',
    projectId: 'thickthock',
    storageBucket: 'thickthock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWJQNDEZPqYzaSnazO7gN6agnqw7tWsY',
    appId: '1:317429734420:ios:f24ed45a3a305bcba11b01',
    messagingSenderId: '317429734420',
    projectId: 'thickthock',
    storageBucket: 'thickthock.appspot.com',
    iosBundleId: 'com.example.challenge',
  );
}
